/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PomieszczenieJDialog.java
 *
 * Created on 2011-04-19, 17:22:17
 */

package View.budynek;

import Controller.ElementyBudynku.Pokoj;
import Model.DAO.MsPokojDAO;
import Model.DAO.MsUrzadzenieDAO;
import Model.Utils.ConnectionManager;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Michał
 */
public class PomieszczenieJDialog extends javax.swing.JDialog {

    /** Creates new form PomieszczenieJDialog */
    public PomieszczenieJDialog(int id, String pok) throws SQLException {
        ConnectionManager.getDatabaseConnection();
        this.pokoj = pok;
        this.idPokoju = id;
        init();

    }
    public PomieszczenieJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        edytuj = new javax.swing.JButton();
        usun = new javax.swing.JButton();
        dodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        edytuj.setText("Ustal parametry urządzenia");
        edytuj.setName("edytuj"); // NOI18N
        edytuj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edytujMouseClicked(evt);
            }
        });

        usun.setText("Usuń urządzenie");
        usun.setName("usun"); // NOI18N
        usun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usunMouseClicked(evt);
            }
        });

        dodaj.setText("Dodaj urządzenie");
        dodaj.setName("dodaj"); // NOI18N
        dodaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dodajMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usun)
                        .addGap(18, 18, 18)
                        .addComponent(edytuj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edytuj)
                    .addComponent(usun)
                    .addComponent(dodaj))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    DefaultListModel model;
    String pokoj;
     int idPokoju;
     List urzadzenia;
     MsUrzadzenieDAO baza;

    private void init(){
        jLabel1.setText(pokoj);
        model  = new DefaultListModel();
        jList1.setModel(model);
        baza = new MsUrzadzenieDAO();

        int n;
        urzadzenia = (new MsPokojDAO()).wylistujUrzadzenia(idPokoju);
        n = urzadzenia.size();
        String nazwaUrzadzenia;
        for (int i = 0; i < n; i++) {
            nazwaUrzadzenia = (new MsUrzadzenieDAO()).pobierzNazwa((Integer)urzadzenia.get(i))+"#"+urzadzenia.get(i);
            model.addElement(nazwaUrzadzenia);

        }
    }
    private void edytujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edytujMouseClicked
       //edytowanie urzadzenia

        String urzadzenie = (String)jList1.getSelectedValue();
        String[] parser = urzadzenie.split("#");
        int i = parser.length;
        int id = Integer.parseInt(parser[i-1]);


       
}//GEN-LAST:event_edytujMouseClicked

    private void usunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usunMouseClicked
       //Usuwanie urzadzenia
        int idlist = jList1.getSelectedIndex();
        String urzadzenie = (String)jList1.getSelectedValue();
        String[] parser = urzadzenie.split("#");
        int i = parser.length;
        int id = Integer.parseInt(parser[i-1]);
        model.remove(idlist);
        baza.usun(id);
        jList1.clearSelection();
    }//GEN-LAST:event_usunMouseClicked

    private void dodajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dodajMouseClicked
        String urzadzenie = (String)jList1.getSelectedValue();
        String[] parser = urzadzenie.split("#");
        int i = parser.length;
        int id = Integer.parseInt(parser[i-1]);

        int nr = 9;
        if (parser[0].compareTo("Alarm") == 0)
            nr = 0;
        else if ((parser[0].compareTo("Analizator") == 0))
            nr = 1;
        else if ((parser[1].compareTo("Czujnik ruchu") == 0))
            nr = 2;
        else if ((parser[1].compareTo("Czujnik temperatury") == 0))
            nr = 3;
        else if ((parser[0].compareTo("Gniazdko") == 0))
            nr = 4;
        else if ((parser[0].compareTo("Klimatyzator") == 0))
            nr = 5;
        else if ((parser[1].compareTo("Punkt grzewczy") == 0))
            nr = 6;
        else if ((parser[1].compareTo("Punkt świetlny") == 0))
            nr = 7;
        else if ((parser[0].compareTo("Zraszacz przeciwpożarowy") == 0))
            nr = 8;

    }//GEN-LAST:event_dodajMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PomieszczenieJDialog dialog = new PomieszczenieJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        try {
                            ConnectionManager.disconnectFromDatabase();
                        } catch (SQLException ex) {
                            Logger.getLogger(PomieszczenieJDialog.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodaj;
    private javax.swing.JButton edytuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton usun;
    // End of variables declaration//GEN-END:variables

}
