/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EdytujBudynek.java
 *
 * Created on 2011-04-23, 19:31:53
 */
package View;

import Controller.ElementyBudynku.Budynek;

/**
 *
 * @author matemroz
 */
public class EdytujBudynek extends javax.swing.JDialog {

    /** Creates new form EdytujBudynek */
    public EdytujBudynek(java.awt.Frame parent, boolean modal, String s, int idListy) {
        super(parent, modal);
        initComponents();
        this.s = s;
        tfNazwaBudynku.setText(s.split("#")[0]);
        this.index = Integer.parseInt(s.split("#")[1]);
        this.idListy = idListy;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNazwaBudynku = new javax.swing.JTextField();
        btnEdytujBudynek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edytu budynek");

        jLabel1.setText("Nazwa:");
        jLabel1.setName("jLabel1"); // NOI18N

        tfNazwaBudynku.setName("tfNazwaBudynku"); // NOI18N

        btnEdytujBudynek.setText("Edytuj");
        btnEdytujBudynek.setName("btnEdytujBudynek"); // NOI18N
        btnEdytujBudynek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEdytujBudynekMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnEdytujBudynek))
                    .addComponent(tfNazwaBudynku, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNazwaBudynku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdytujBudynek)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-198)/2, (screenSize.height-118)/2, 198, 118);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEdytujBudynekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEdytujBudynekMouseClicked
        Budynek b = new Budynek();
        if (!tfNazwaBudynku.getText().equals(s)) {
            b.ustawNazwa(index, tfNazwaBudynku.getText());
            (View.ProjektorPanel.getLstBudynki()).set(idListy, tfNazwaBudynku.getText()+"#"+index);
            dispose();
        }
    }//GEN-LAST:event_btnEdytujBudynekMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EdytujBudynek dialog = new EdytujBudynek(new javax.swing.JFrame(), true, new String(), 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdytujBudynek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfNazwaBudynku;
    // End of variables declaration//GEN-END:variables
    private String s;
    private int index;
    private int idListy;
}
